defmodule TMI.Chat.Parsing.EventMapping do
  @moduledoc false

  @events %{
    #   "" => :announcement,
    #   "" => :charity_donation,
    #   "" => :channel_update,
    #   "" => :cheer,
    #   "" => :ban,
    #   "" => :unban,
    #   "" => :moderator_add,
    #   "" => :moderator_remove,
    #   "" => :guest_star_session_begin,
    #   "" => :guest_star_session_end,
    #   "" => :guest_star_guest,
    #   "" => :guest_star_settings_update,
    #   "" => :clear,
    #   "" => :clear_user_messages,
    #   "" => :message_delete,
    #   "" => :message,
    #   "" => :cheermote,
    "emote_only_on" => :emote_only_on,
    "emote_only_off" => :emote_only_off,
    #   "" => :mention,
    #   "" => :setting_update,
    #   "" => :follow,
    #   "" => :ad_break,
    #   "" => :sub,
    #   "" => :sub_message,
    #   "" => :sub_end,
    "resub" => :resub,
    #   "" => :sub_gift,
    "submysterygift" => :community_sub_gift,
    "subgift" => :sub_gift,
    "sub" => :sub,
    "giftpaidupgrade" => :gift_paid_upgrade,
    "primepaidupgrade" => :prime_paid_upgrade,
    "raid" => :raid,
    "unraid" => :unraid,
    "communitypayforward" => :pay_it_forward,
    "highlighted-message" => :highlighted_message,
    #   "" => :messge,
    #   "" => :reward_add,
    #   "" => :reward_remove,
    #   "" => :reward_redemption,
    #   "" => :reward_redemption_update,
    #   "" => :poll_begin,
    #   "" => :poll_progress,
    #   "" => :poll_end,
    #   "" => :prediction_begin,
    #   "" => :prediction_progress,
    #   "" => :prediction_end,
    #   "" => :charity_campaign_donate,
    #   "" => :charity_campaign_progress,
    #   "" => :charity_campaign_start,
    #   "" => :charity_campaign_stop,
    #   "" => :drop_entitlement_grant,
    #   "" => :extension_bit_transaction,
    #   "" => :goal_begin,
    #   "" => :goal_progress,
    #   "" => :goal_end,
    #   "" => :hype_train_begin,
    #   "" => :hype_train_progress,
    #   "" => :hype_train_end,
    #   "" => :shield_mode_begin,
    #   "" => :shield_mode_end,
    #   "" => :shoutout_create,
    #   "" => :shoutout_receive,
    #   "" => :stream_online,
    #   "" => :stream_offline,
    #   "" => :user_auth_grant,
    #   "" => :user_auth_revoke,
    #   "" => :user_update,
    "viewermilestone" => :viewer_milestone,
    # WTF ಠ_ಠ
    "msg_emoteonly" => :unrecognized
  }

  @doc """
  Get the event name from the IRC `msg-id` tag event identifier.
  """
  @spec event_name!(String.t()) :: atom()
  def event_name!(irc_event), do: Map.fetch!(@events, irc_event)
end
